repos:
    # Python: Ruff for Linting and Formatting
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.0 # Use the latest version
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    # Web: Prettier for TS, React, and JSON
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.11
      hooks:
          - id: prettier
            types_or: [javascript, jsx, typescript, tsx, json, css, markdown]
            # Only runs on files in your frontend directory if needed:
            files: ^front-end/
